= AS-E User Documentation

== Introduction

The second release of this application bridges the gap between a text-mining pipeline using the AlvisNLP/ML platform and the parent application FLAGdb++. Text-mining annotations are made available for search through the application's interface.

Named-entity recognition has been applied on a corpus about __Arabidopsis thaliana__ and the resulting data has been integrated into a __beta__ version of the FLAGdb++ application. The annotations can be accessed from the FLAGdb++ interface, as well as from the standalone search engine of the first release (available at http://bibliome.jouy.inra.fr/demo/seedev/alvisir/webapi/search?).



== Data Processing Scenarios

In AS-E, we have outlined the following data processing scenarios:

* <<application_design.adoc#, Application design>> (corpus building, resources gathering, etc.)
* <<production_processing.adoc#, Production processing>> (automatic annotation of a corpus by a text-mining pipeline and integration of the results into a parent application)
* <<resource_update.adoc#, Resource update>> (corpus increment, external resource update)

The application into which the text-mining data has been integrated is part of the "Production processing" scenario and the visualization that has been implemented is documented <<flagdb++_doc.adoc#, here>>. A user already making use of the FLAGdb++ application may now access text mining annotations in a similar way to the access to genomic data. A tutorial is provided in the parent application documentation.
