= AS-E User Documentation

== Introduction

Building on the first release of this use-case, named-entity recognition has been applied on a corpus about __Arabidopsis thaliana__ and the resulting data has been integrated into the FLAGdb++ client application. These annotations can be queried using a __beta__ version of the FLAGdb++ application. The semantic search engine provided in the first release indexes the same data and can be both accessed from FLAGAdb++ — in which annotations link to the context of the document, as well as a standalone search engine.

== Data Processing Scenarios

In AS-E, we have outlined the following data processing scenarios:

* <<application_design.adoc#, Application design>> (corpus building, resources gathering, etc.)
* <<production_processing.adoc#, Production processing>> (automatic annotation of a corpus by a text-mining pipeline and integration of the results into a parent application)
* <<resource_update.adoc#, Resource update>> (corpus increment, external resource update)

The web application of this first release is part of the "Production processing" scenario and is fully documented <<web_app_doc.adoc#, here>>. As the results of the text-mining pipeline could not be integrated into the host application targeted by this use case at the time of the first release, we integrated them into the above-mentioned web application instead. This semantic search engine is close to what will be available in the final application since it provides an easier access to information about seed development from the scientific literature. 
