= AS-E User Documentation

== Introduction

Building on the first release of this use-case, named-entity recognition has been applied on a corpus about __Arabidopsis thaliana__ and the resulting data has been integrated into the FLAGdb++ client application. These annotations can be queried using a __beta__ version of the FLAGdb++ application. The semantic search engine provided in the first release indexes the same data and can be both accessed from FLAGAdb++ — in which annotations link to the context of the document, as well as a standalone search engine.

== Data Processing Scenarios

In AS-E, we have outlined the following data processing scenarios:

* <<application_design.adoc#, Application design>> (corpus building, resources gathering, etc.)
* <<production_processing.adoc#, Production processing>> (automatic annotation of a corpus by a text-mining pipeline and integration of the results into a parent application)
* <<resource_update.adoc#, Resource update>> (corpus increment, external resource update)

The application into which the text-mining data has been integrated is part of the "Production processing" scenario and the visualization that has been implemented is documented <<flagdb++_doc.adoc#, here>>. A user already making use of the FLAGdb++ application may now access text mining annotations in a similar way to the access to genomic data. A tutorial is provided in the parent application documentation.
