= Production processing

== Automatic annotation of a corpus

The AS-E text-mining pipeline automatically extracts the following entities:

* Genes
* Proteins
* RNA

All configuration files, AlvisNLP workflow plans, scripts, and resources used to create the AS-E text-mining pipeline are provided in the uc-tdm-AS-E repository in the openminted github (https://github.com/openminted/uc-tdm-AS-E). Documentation for running the pipeline to annotate and index a corpus is also included in the repository.

== Integration into a parent application

The text-mining annotations have been integrated into the parent application FLAGdb++ enabling a researcher to browse the Abrabidopsis genome and access text-mining annotations as well as genomic data integrated into FLAGdb++.

Moreover, the same annotations are indexed by the semantic search engine of the first release and can be accessed directly, through the search interface available at http://bibliome.jouy.inra.fr/demo/seedev/alvisir/webapi/search?.


Detailed documentation, including a tutorial guiding the user on the interface can be found in the <<parent-application#, FLAGdb++ documentation>>.

Detailed documentation on how to use the search engine can be found in the <<web_app_doc.adoc#, AS-E web application documentation>>.

